"""create auth tables

Revision ID: 2973ab3fcccd
Revises: 64e3395b5617
Create Date: 2026-04-10 00:05:38.223407
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2973ab3fcccd'
down_revision: Union[str, None] = '64e3395b5617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
