"""create finance tables

Revision ID: 51fba7fd95da
Revises: 9dac5590e8b7
Create Date: 2026-04-16 22:08:03.591989
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51fba7fd95da'
down_revision: Union[str, None] = '9dac5590e8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_categories_direction'), 'finance_categories', ['direction'], unique=False)
    op.create_index(op.f('ix_finance_categories_id'), 'finance_categories', ['id'], unique=False)
    op.create_index(op.f('ix_finance_categories_name'), 'finance_categories', ['name'], unique=False)
    op.create_table('finance_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('service_order_id', sa.UUID(), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_transactions_category_id'), 'finance_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_customer_id'), 'finance_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_direction'), 'finance_transactions', ['direction'], unique=False)
    op.create_index(op.f('ix_finance_transactions_due_date'), 'finance_transactions', ['due_date'], unique=False)
    op.create_index(op.f('ix_finance_transactions_id'), 'finance_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_operation_id'), 'finance_transactions', ['operation_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_service_order_id'), 'finance_transactions', ['service_order_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_status'), 'finance_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_finance_transactions_supplier_id'), 'finance_transactions', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_transactions_supplier_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_status'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_service_order_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_operation_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_due_date'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_direction'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_customer_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_category_id'), table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_index(op.f('ix_finance_categories_name'), table_name='finance_categories')
    op.drop_index(op.f('ix_finance_categories_id'), table_name='finance_categories')
    op.drop_index(op.f('ix_finance_categories_direction'), table_name='finance_categories')
    op.drop_table('finance_categories')
    # ### end Alembic commands ###
