"""create vehicles and drivers

Revision ID: cfd12c32ef33
Revises: 8b106a6a88c2
Create Date: 2026-04-10 12:18:17.757127
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cfd12c32ef33'
down_revision: Union[str, None] = '8b106a6a88c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('renavam', sa.String(length=20), nullable=True),
    sa.Column('chassis', sa.String(length=30), nullable=True),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year_manufacture', sa.Integer(), nullable=False),
    sa.Column('year_model', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('axis_count', sa.Integer(), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('capacity_m3', sa.Float(), nullable=True),
    sa.Column('odometer', sa.Float(), nullable=False),
    sa.Column('horimeter', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('crlv_expiry', sa.Date(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('insurance_policy', sa.String(length=50), nullable=True),
    sa.Column('antt_code', sa.String(length=30), nullable=True),
    sa.Column('antt_expiry', sa.Date(), nullable=True),
    sa.Column('tracker_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassis'),
    sa.UniqueConstraint('renavam')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_tracker_id'), 'vehicles', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('cnh_number', sa.String(length=20), nullable=False),
    sa.Column('cnh_category', sa.String(length=5), nullable=False),
    sa.Column('cnh_expiry', sa.Date(), nullable=False),
    sa.Column('cnh_first_issue', sa.Date(), nullable=True),
    sa.Column('mopp', sa.Boolean(), nullable=False),
    sa.Column('mopp_expiry', sa.Date(), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('current_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh_number')
    )
    op.create_index(op.f('ix_drivers_cpf'), 'drivers', ['cpf'], unique=True)
    op.create_index(op.f('ix_drivers_current_vehicle_id'), 'drivers', ['current_vehicle_id'], unique=False)
    op.create_index(op.f('ix_drivers_full_name'), 'drivers', ['full_name'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_full_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_current_vehicle_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_cpf'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_tracker_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
