"""create operations

Revision ID: db494ce788ae
Revises: cfd12c32ef33
Create Date: 2026-04-12 09:24:57.057665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db494ce788ae'
down_revision: Union[str, None] = 'cfd12c32ef33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('origin_description', sa.String(length=300), nullable=False),
    sa.Column('origin_city', sa.String(length=100), nullable=True),
    sa.Column('origin_state', sa.String(length=2), nullable=True),
    sa.Column('origin_latitude', sa.Float(), nullable=True),
    sa.Column('origin_longitude', sa.Float(), nullable=True),
    sa.Column('destination_description', sa.String(length=300), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=True),
    sa.Column('destination_state', sa.String(length=2), nullable=True),
    sa.Column('destination_latitude', sa.Float(), nullable=True),
    sa.Column('destination_longitude', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=True),
    sa.Column('cargo_description', sa.String(length=500), nullable=True),
    sa.Column('cargo_weight_kg', sa.Float(), nullable=True),
    sa.Column('cargo_volume_m3', sa.Float(), nullable=True),
    sa.Column('odometer_start', sa.Float(), nullable=True),
    sa.Column('odometer_end', sa.Float(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_code'), 'operations', ['code'], unique=True)
    op.create_index(op.f('ix_operations_customer_id'), 'operations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_operations_driver_id'), 'operations', ['driver_id'], unique=False)
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.create_index(op.f('ix_operations_status'), 'operations', ['status'], unique=False)
    op.create_index(op.f('ix_operations_vehicle_id'), 'operations', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_vehicle_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_status'), table_name='operations')
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_driver_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_customer_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_code'), table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
